[build]
  publish   = "."                       # deploy from root
  functions = "netlify/functions"       # your serverless API

# Redirect /admin to your new function-based panel
[[redirects]]
  from   = "/admin/*"
  to     = "/.netlify/functions/admin_server/:splat"
  status = 200
  force  = true

# Also catch direct hits to /admin-panel-private.html and send to the function
[[redirects]]
  from   = "/admin-panel-private.html"
  to     = "/.netlify/functions/admin_server/"
  status = 200
  force  = true
