[build]
  # Deploy everything from the repo root
  publish   = "."
  # Your serverless functions folder
  functions = "netlify/functions"

[[redirects]]
  # Catch /admin and proxy it to your new admin app
  from     = "/admin/*"
  to       = "/.netlify/functions/admin_server/:splat"
  status   = 200
  force    = true
