[build]
  publish    = "public"               # adjust if your HTML lives elsewhere
  functions  = "netlify/functions"    # where our backend will live

[[redirects]]
  from   = "/admin/*"
  to     = "/.netlify/functions/admin_server/:splat"
  status = 200
