[build]
  publish   = "."                # deploy from the repo root
  functions = "netlify/functions"

[[redirects]]
  from   = "/admin/*"
  to     = "/admin/index.html"
  status = 200
  force  = true
